name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ajuwayne96
          outputs: |
            ./dist/github-contribution-grid-snake.svg
          # 🎨 Customize colors
          color_snake: '#1e3a8a'      # Tail color (Dark blue)
          color_dots: '#0f172a,#1e293b,#334155,#475569,#1e40af'  # gradient-like blue shades
